// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eHealth.Data;

#nullable disable

namespace eHealth.Migrations
{
    [DbContext(typeof(DoctorContext))]
    [Migration("20240125081204_addMigration")]
    partial class addMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("eHealth.Models.Doctor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("birthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("imageFile")
                        .HasColumnType("BLOB");

                    b.Property<string>("imageMimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("imageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("inami")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            id = 1,
                            birthDate = new DateOnly(2024, 1, 25),
                            firstName = "Shawna",
                            imageMimeType = "image/jpeg",
                            imageName = "shawna_trejo.jpg",
                            inami = "7055",
                            lastName = "Trejo"
                        },
                        new
                        {
                            id = 2,
                            birthDate = new DateOnly(2024, 1, 25),
                            firstName = "Rod",
                            imageMimeType = "image/jpeg",
                            imageName = "rod_hale.jpg",
                            inami = "4478",
                            lastName = "Hale"
                        },
                        new
                        {
                            id = 3,
                            birthDate = new DateOnly(2024, 1, 25),
                            firstName = "Christopher",
                            imageMimeType = "image/jpeg",
                            imageName = "christopher_green.jpg",
                            inami = "588",
                            lastName = "Green"
                        },
                        new
                        {
                            id = 4,
                            birthDate = new DateOnly(2024, 1, 25),
                            firstName = "Debra",
                            imageMimeType = "image/jpeg",
                            imageName = "debra_meyer.jpg",
                            inami = "9077",
                            lastName = "Meyers"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
