// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eHealth.Data;

#nullable disable

namespace eHealth.Migrations.Patient
{
    [DbContext(typeof(PatientContext))]
    [Migration("20240126141014_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("eHealth.Models.Patient", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChronicConditions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyMedicalHistory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuranceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Medications")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PastMedicalHistory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialHistory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Age = 324,
                            BirthDate = "13/07/1994",
                            ChronicConditions = "Chronic Conditions text details pour mon patiet est = bla bla bla bla bla ...",
                            Contact = "0484666560",
                            Description = "Description 01",
                            FamilyMedicalHistory = "Family Medical History text details pour mon patiet est = bla bla bla bla bla ...",
                            FullName = "Erling Haland",
                            Gender = "Homme",
                            InsuranceNumber = "NI-8956",
                            Medications = "Medications text details pour mon patiet est = bla bla bla bla bla ...",
                            PastMedicalHistory = "Past Medical History text details pour mon patiet est = bla bla bla bla bla ...",
                            SocialHistory = "Marié"
                        },
                        new
                        {
                            id = 2,
                            Age = 326,
                            BirthDate = "13/07/1994",
                            ChronicConditions = "Chronic Conditions text details pour mon patiet est = bla bla bla bla bla ...",
                            Contact = "0484666560",
                            Description = "Description 02",
                            FamilyMedicalHistory = "Family Medical History text details pour mon patiet est = bla bla bla bla bla ...",
                            FullName = "Kilian Empapé",
                            Gender = "Homme",
                            InsuranceNumber = "NI-8956",
                            Medications = "Medications text details pour mon patiet est = bla bla bla bla bla ...",
                            PastMedicalHistory = "Past Medical History text details pour mon patiet est = bla bla bla bla bla ...",
                            SocialHistory = "Marié"
                        },
                        new
                        {
                            id = 3,
                            Age = 34,
                            BirthDate = "13/07/1994",
                            ChronicConditions = "Chronic Conditions text details pour mon patiet est = bla bla bla bla bla ...",
                            Contact = "0484666560",
                            Description = "Description 03",
                            FamilyMedicalHistory = "Family Medical History text details pour mon patiet est = bla bla bla bla bla ...",
                            FullName = "Lionel Messi",
                            Gender = "Homme",
                            InsuranceNumber = "NI-8956",
                            Medications = "Medications text details pour mon patiet est = bla bla bla bla bla ...",
                            PastMedicalHistory = "Past Medical History text details pour mon patiet est = bla bla bla bla bla ...",
                            SocialHistory = "Marié"
                        },
                        new
                        {
                            id = 4,
                            Age = 38,
                            BirthDate = "13/07/1994",
                            ChronicConditions = "Chronic Conditions text details pour mon patiet est = bla bla bla bla bla ...",
                            Contact = "0484666560",
                            Description = "Description 04",
                            FamilyMedicalHistory = "Family Medical History text details pour mon patiet est = bla bla bla bla bla ...",
                            FullName = "Cristiano Renaldo",
                            Gender = "Homme",
                            InsuranceNumber = "NI-8956",
                            Medications = "Medications text details pour mon patiet est = bla bla bla bla bla ...",
                            PastMedicalHistory = "Past Medical History text details pour mon patiet est = bla bla bla bla bla ...",
                            SocialHistory = "Marié"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
